In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [2]:
# path to dataframes
path_to_dfs = "forecasted_counts/block_0104/"

In [3]:
# os.listdir(path_to_dfs)

In [4]:
averaged_forecasts_csvs = []
for file in os.listdir(path_to_dfs):
    if file[:8] =='averaged':
        averaged_forecasts_csvs.append(file)

In [5]:
averaged_forecasts_csvs.sort()
averaged_forecasts_csvs

['averaged_forecasts_sub_0.csv',
 'averaged_forecasts_sub_1.csv',
 'averaged_forecasts_sub_10.csv',
 'averaged_forecasts_sub_11.csv',
 'averaged_forecasts_sub_2.csv',
 'averaged_forecasts_sub_3.csv',
 'averaged_forecasts_sub_4.csv',
 'averaged_forecasts_sub_5.csv',
 'averaged_forecasts_sub_6.csv',
 'averaged_forecasts_sub_7.csv',
 'averaged_forecasts_sub_8.csv',
 'averaged_forecasts_sub_9.csv']

In [6]:
# add the 10, 11 at the end
csv_files_10_11 = ['averaged_forecasts_sub_10.csv', 'averaged_forecasts_sub_11.csv']

In [7]:
other_files = [i for i in averaged_forecasts_csvs if i not in csv_files_10_11]

In [8]:
ordered_csv_files = other_files + csv_files_10_11

In [9]:
ordered_csv_files

['averaged_forecasts_sub_0.csv',
 'averaged_forecasts_sub_1.csv',
 'averaged_forecasts_sub_2.csv',
 'averaged_forecasts_sub_3.csv',
 'averaged_forecasts_sub_4.csv',
 'averaged_forecasts_sub_5.csv',
 'averaged_forecasts_sub_6.csv',
 'averaged_forecasts_sub_7.csv',
 'averaged_forecasts_sub_8.csv',
 'averaged_forecasts_sub_9.csv',
 'averaged_forecasts_sub_10.csv',
 'averaged_forecasts_sub_11.csv']

In [10]:
all_dfs = []
for file in ordered_csv_files:
    read_df = pd.read_csv(path_to_dfs + '/' + file)
    all_dfs.append(read_df)

In [11]:
# make a single dataframe out of the many
combined_df = pd.concat(all_dfs, axis = 1)

In [12]:
combined_df.head()

True_value  Forecasted_value  True_value  Forecasted_value  True_value  \
0         3.0          3.090382    5.000000          4.345422    3.000000   
1         3.0          3.357837    3.885234          4.337047    4.999504   
2         4.0          2.777556    4.996880          4.704496    5.002446   
3         4.0          3.519596    6.267051          5.766768    4.678494   
4         3.0          3.583932    5.976258          5.865704    2.748851   

   Forecasted_value  True_value  Forecasted_value  True_value  \
0          3.965861         0.0          0.404849    5.035696   
1          4.022651         0.0          0.421353    4.080343   
2          4.848159         0.0          0.862991    4.691607   
3          3.966531         0.0         -0.301113    4.000000   
4          3.956424         1.0          0.181418    5.211974   

   Forecasted_value  ...  True_value  Forecasted_value  True_value  \
0          3.746100  ...    0.002516          0.720516    2.000000   
1          3.796304  ...    0.000000          1.126536    3.000000   
2          3.663024  ...    0.000000          0.808601    3.964335   
3          4.191371  ...    0.999995          0.949014    2.000000   
4          4.328288  ...    1.999969          0.698139    3.021878   

   Forecasted_value  True_value  Forecasted_value  True_value  \
0          1.983630    3.999930          3.439458    1.000013   
1          1.665170    2.963009          3.509813    0.345385   
2          2.287876    3.884737          3.351333    2.000670   
3          0.805012    4.000000          3.584534    2.344058   
4          1.028499    4.633545          3.490240    2.080343   

   Forecasted_value  True_value  Forecasted_value  
0          1.667192    0.997484          1.120003  
1          1.481683    0.000000          1.063996  
2          1.556076    0.000000          1.071001  
3          1.650069    1.000005          0.570715  
4          1.619888    2.000000          0.777397  

[5 rows x 24 columns]

In [13]:
combined_df.shape

(7, 24)

In [14]:
# get the true values
True_values_df = combined_df[['True_value']]

In [15]:
True_values_df

True_value  True_value  True_value  True_value  True_value  True_value  \
0    3.000000    5.000000    3.000000    0.000000    5.035696    6.964375   
1    3.000000    3.885234    4.999504    0.000000    4.080343    6.067392   
2    4.000000    4.996880    5.002446    0.000000    4.691607    8.339459   
3    4.000000    6.267051    4.678494    0.000000    4.000000    9.696634   
4    3.000000    5.976258    2.748851    1.000000    5.211974    7.132603   
5    4.885411    5.115885    3.156840    3.125455    5.502185    6.496521   
6    3.000000    2.344058    3.002520    3.002801    2.000001    7.447157   

   True_value  True_value  True_value  True_value  True_value  True_value  
0    1.999987    0.002516    2.000000    3.999930    1.000013    0.997484  
1    1.659135    0.000000    3.000000    2.963009    0.345385    0.000000  
2    2.119867    0.000000    3.964335    3.884737    2.000670    0.000000  
3    1.013762    0.999995    2.000000    4.000000    2.344058    1.000005  
4    2.193389    1.999969    3.021878    4.633545    2.080343    2.000000  
5    1.788700    3.043554    3.211298    3.788700    1.054460    1.000000  
6    1.999996    0.000000    2.000160    4.208624    1.000000    0.000000

In [16]:
# sum the true values - since the sub images are not overlapping, we can get the sum across columns in the above dataframe
sum_true_values = True_values_df.sum(axis = 1)

In [17]:
sum_true_values

0    33.000000
1    30.000000
2    39.000001
3    40.000001
4    40.998811
5    42.169009
6    30.005317
dtype: float64

In [18]:
# get the forecasted values
Forecasted_values_df = combined_df[['Forecasted_value']]

In [19]:
Forecasted_values_df

Forecasted_value  Forecasted_value  Forecasted_value  Forecasted_value  \
0          3.090382          4.345422          3.965861          0.404849   
1          3.357837          4.337047          4.022651          0.421353   
2          2.777556          4.704496          4.848159          0.862991   
3          3.519596          5.766768          3.966531         -0.301113   
4          3.583932          5.865704          3.956424          0.181418   
5          3.266204          6.283763          3.989910          0.490976   
6          3.256188          5.846380          3.971091          0.158528   

   Forecasted_value  Forecasted_value  Forecasted_value  Forecasted_value  \
0          3.746100          3.893562          2.360484          0.720516   
1          3.796304          3.869701          2.320263          1.126536   
2          3.663024          4.157682          1.990893          0.808601   
3          4.191371          3.872577          3.758284          0.949014   
4          4.328288          3.735846          4.300022          0.698139   
5          4.235282          3.898197          2.578542          1.079273   
6          4.186745          3.987216          3.109307          0.549958   

   Forecasted_value  Forecasted_value  Forecasted_value  Forecasted_value  
0          1.983630          3.439458          1.667192          1.120003  
1          1.665170          3.509813          1.481683          1.063996  
2          2.287876          3.351333          1.556076          1.071001  
3          0.805012          3.584534          1.650069          0.570715  
4          1.028499          3.490240          1.619888          0.777397  
5          0.336472          3.805908          1.671351          0.739065  
6          1.036284          4.127296          1.696865          0.603353

In [20]:
Forecasted_values_df.shape

(7, 12)

In [21]:
sum_forecasted_values = Forecasted_values_df.sum(axis = 1)

In [22]:
sum_forecasted_values

0    30.737459
1    30.972355
2    32.079689
3    32.333357
4    33.565798
5    32.374945
6    32.529211
dtype: float64

In [23]:
# concatenate the sum dataframes
block_0104_true_and_forecasted_values_df = pd.concat((sum_true_values, sum_forecasted_values), axis = 1)

In [24]:
block_0104_true_and_forecasted_values_df.columns = ["True_count", "Forecasted_count"]

In [25]:
block_0104_true_and_forecasted_values_df

True_count  Forecasted_count
0   33.000000         30.737459
1   30.000000         30.972355
2   39.000001         32.079689
3   40.000001         32.333357
4   40.998811         33.565798
5   42.169009         32.374945
6   30.005317         32.529211

In [26]:
block_0104_true_and_forecasted_values_df.to_csv("final_forecasted_counts/block_0104_finals_forecasts.csv", index = False)

In [27]:
# # well we need to verify that the above true values are indeed correct
# from preprocess script we have the following counts
# [43, 49, 53, 59, 45, 42, 34, 39, 37, 43, 41, 39, 43, 40, 39, 41, 31, 32, 40, 29] # the last seven numbers match with what we have.

In [28]:
# blockwise mean squared error
rmse = np.sqrt(mean_squared_error(sum_true_values, sum_forecasted_values))
rmse

6.213764968258293

In [29]:
# blockwise mean absolute error
mae = mean_absolute_error(sum_true_values, sum_forecasted_values)
mae

5.367546107821808

In [30]:
# Getting the coverages and the widths for the forecasted values - This can be done with the saved all forecasts npy files
# location for the forecast files (all forecasts)
location_all_forecasts = 'forecasted_counts/block_0104'

# contents at this location
all_contents = os.listdir(location_all_forecasts)
all_contents.sort()

In [31]:
# we need the npy files for all forecasts
all_forecast_files = [file for file in all_contents if file[:3] == 'all']

In [32]:
# arange the files in order
later_npy_files = ['all_forecasts_sub_10.npy', 'all_forecasts_sub_11.npy']
first_files = [file for file in all_forecast_files if file not in later_npy_files]

In [33]:
final_all_forecast_files = first_files + later_npy_files

In [34]:
final_all_forecast_files

['all_forecasts_sub_0.npy',
 'all_forecasts_sub_1.npy',
 'all_forecasts_sub_2.npy',
 'all_forecasts_sub_3.npy',
 'all_forecasts_sub_4.npy',
 'all_forecasts_sub_5.npy',
 'all_forecasts_sub_6.npy',
 'all_forecasts_sub_7.npy',
 'all_forecasts_sub_8.npy',
 'all_forecasts_sub_9.npy',
 'all_forecasts_sub_10.npy',
 'all_forecasts_sub_11.npy']

In [35]:
loaded_npy_files = []
for file in final_all_forecast_files:
    joined_path = os.path.join(location_all_forecasts, file)
    load_file = np.load(joined_path)
    loaded_npy_files.append(load_file)

In [36]:
len(loaded_npy_files)

12

In [37]:
output = sum(loaded_npy_files)

In [38]:
output.shape

(1000, 4, 7)

In [39]:
final_array = output.reshape(4000,7)

In [40]:
final_array

array([[30.289557, 28.149418, 24.19578 , ..., 36.761703, 42.41029 ,
        62.847298],
       [23.974836, 30.433416, 23.879543, ..., 35.37668 , 40.820133,
        34.000633],
       [24.286087, 34.472332, 23.576845, ..., 19.764013, 20.226458,
        29.617722],
       ...,
       [31.908293, 24.577797, 27.64894 , ..., 39.340336, 25.279364,
        32.378395],
       [28.35446 , 34.587856, 29.27621 , ..., 23.334278, 33.145123,
        36.254562],
       [26.42628 , 32.170025, 29.67711 , ..., 28.403378, 25.643152,
        22.763128]], dtype=float32)

In [41]:
li_train = np.percentile(final_array, axis = 0, q = (2.5, 97.5))[0,:].reshape(-1,1)    
ui_train = np.percentile(final_array, axis = 0, q = (2.5, 97.5))[1,:].reshape(-1,1)

In [42]:
li_train

array([[19.47134061],
       [18.68034563],
       [20.35248752],
       [18.25764036],
       [16.78010378],
       [14.53195755],
       [10.9002497 ]])

In [43]:
ui_train

array([[41.61416979],
       [42.64579172],
       [42.44498062],
       [46.47115459],
       [49.3372385 ],
       [49.38569136],
       [53.74965582]])

In [44]:
width_train = ui_train - li_train
avg_width_train = width_train.mean(0)[0]

In [45]:
avg_width_train

29.52493675095695

In [46]:
y_traina = block_0104_true_and_forecasted_values_df[["True_count"]].values

In [47]:
ind_train = (y_traina >= li_train) & (y_traina <= ui_train)
coverage_train= ind_train.mean(0)[0]

In [48]:
coverage_train

1.0

Verify the true counts we have for the test data are indeed correct

In [49]:
# Verify the true counts - from np arrays - location Block_0103/sub_images_and_counts

sub_count_loc = 'all_preprocessed_data/Block_0104/sub_images_and_counts'

In [50]:
sub_density_maps = [i for i in os.listdir(sub_count_loc) if i.split(".")[0][-7:] == 'density']
sub_density_maps.sort()

In [51]:
# get the test dates
test_time_periods = ['2020_08_26', '2020_08_27', '2020_08_28' ,'2020_08_31', '2020_09_02', '2020_09_07', '2020_09_16']

In [52]:
test_time_periods = ['Block0104_' + i for i in test_time_periods]

In [53]:
# print the test dates
test_time_periods

['Block0104_2020_08_26',
 'Block0104_2020_08_27',
 'Block0104_2020_08_28',
 'Block0104_2020_08_31',
 'Block0104_2020_09_02',
 'Block0104_2020_09_07',
 'Block0104_2020_09_16']

In [54]:
# get the density maps for these days only for the computation of the total true counts of the test images
test_density_maps = [i for i in sub_density_maps if i[:20] in test_time_periods]
test_density_maps.sort()

In [55]:
%%time
# get the true counts
true_counts_in_order = []
step = 0
# we have only seven time points
for u in range(7):
    catch_counts = []
    # for each time steps we have 12 images, and since the sub windows are not overlapping we can add the values straightaway eben without sorting
    for j in range(step, step + 12):
        total_count = np.sum(np.load(os.path.join(sub_count_loc, test_density_maps[j])))
        catch_counts.append(total_count)
    true_counts_in_order.append(np.sum(catch_counts))
    step = step + 12

CPU times: user 41.3 ms, sys: 92.4 ms, total: 134 ms
Wall time: 5.18 s


In [56]:
true_counts_in_order

[33.00000000000001,
 30.000000000000004,
 39.00000127295261,
 40.0,
 40.99881043962578,
 42.16900880475353,
 30.005316665182647]

In [58]:
block_0104_true_and_forecasted_values_df[['True_count']].values.flatten()

array([33.00000045, 30.00000045, 39.00000143, 40.00000054, 40.99881077,
       42.16900909, 30.00531685])

In [60]:
# see if the two values we get match 

In [59]:
np.mean(np.round(true_counts_in_order, 0) == np.round(block_0104_true_and_forecasted_values_df[['True_count']].values.flatten(), 0))

1.0